Adds server data
htmlacademy-react/1309193-six-cities-8 pull request #10
Opened 2021-11-05 20:10 UTC by BorisGvozdetsky

2021-11-06 14:07 UTC, dtsaryov requested changes

2021-11-06 14:07 UTC, dtsaryov commented on project/src/store/action.ts
> +const requireLogout = (): RequireLogoutAction => ({
Зачем еще один экшн, если есть requireAuthorization ?

2021-11-06 14:07 UTC, dtsaryov commented on project/src/store/action.ts
> +const switchSortType = (sortType: SortType): SwitchSortTypeAction => ({
setSortType

2021-11-06 14:07 UTC, dtsaryov commented on project/src/store/api-action.ts
> +const logoutAction = (): ThunkActionResult =>
Убери суффикс "Action" - в нем нет необходимости

2021-11-06 14:07 UTC, dtsaryov commented on project/src/components/place-container/place-container.tsx
> +    setSelectedOffer(undefined);
null, не undefined

2021-11-07 17:30 UTC, BorisGvozdetsky commented on project/src/components/place-container/place-container.tsx
> +    setSelectedOffer(undefined);
Здесь совсем не понял, но он не дает такой тип поставить

2021-11-07 17:31 UTC, BorisGvozdetsky commented on project/src/store/action.ts
> +const requireLogout = (): RequireLogoutAction => ({
Я так понял, что это для второй части задания пригодится. Шел по коммитам.

2021-11-08 21:34 UTC, dtsaryov approved these changes

2021-11-08 21:34 UTC, dtsaryov commented on project/src/components/place-container/place-container.tsx
> +    setSelectedOffer(undefined);
Ну так надо значит указать другой тип )

2021-11-08 21:34 UTC, merged